import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const Legal = () => {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar />
      <div className="flex-grow pt-32 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-gray-900 mb-8">Legal Disclaimer</h1>
          
          <div className="prose prose-lg max-w-none text-gray-600 space-y-6">
            <p>
              The following legal disclaimer applies to your use of AntarangAI and all content, analysis, and information provided through our platform:
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Informational Purposes Only</h3>
            <p>
              The analysis, reports, checklists, and any other content generated by AntarangAI are provided for general informational purposes to help you in your startup journey. This information is not intended to be and does not constitute legal advice, financial advice, or professional consulting specific to your situation. While we include regulatory checklists tailored for India, content may not reflect the most current developments. Always consult with a qualified expert before making decisions.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">No Attorney-Client Relationship</h3>
            <p>
              Using AntarangAI does not create any attorney-client or advisor-client relationship. We are not a law firm or registered financial advisor. The guidance is AI-generated and cannot account for every nuance.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Accuracy and Completeness</h3>
            <p>
              We strive for accuracy but do not guarantee the completeness or timeliness of information. Laws and business conditions change. You should independently verify critical information.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">User Responsibility</h3>
            <p>
              You are solely responsible for how you use the information obtained from AntarangAI. Any actions you take are strictly at your own risk. We are not liable for losses or damages incurred by relying on our analysis.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">No Warranties</h3>
            <p>
              AntarangAI is provided on an “as-is” basis without warranties of any kind, express or implied. We do not warrant that the Service will always be available, error-free, or secure.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Regulatory Compliance</h3>
            <p>
              We operate in compliance with Indian laws. Our guidance informs about regulations like GST or FSSAI but it is your responsibility to ensure full compliance and obtain necessary licenses.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Third-Party Content</h3>
            <p>
              Our platform may contain links to third-party resources for convenience. We do not endorse or assume responsibility for their content.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Confidentiality of User Data</h3>
            <p>
              We consider your ideas and data confidential as described in our Privacy Policy. You are responsible for any sharing of your exported results.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 pt-4">Acceptance of Disclaimer</h3>
            <p>
              By using AntarangAI, you acknowledge that you have read and understood this disclaimer. You accept that any reliance on the Service is at your own risk.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Legal;

